name: candy_core
description: All of the Core Widgets, Classes and Services I use in almost all of my Apps.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.0
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.1.0
  cached_network_image: ^3.2.2
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.1  
  freezed: ^2.1.1
